# -*- coding: utf-8 -*-
"""Paule_ICTS311Lec - Comprehensive Machine Learning Regression Tutorial

Automatically generated by Colab.

TOPIC: Machine Learning - Regression Analysis, Model Evaluation, Cross-Validation, SVM Kernels

PROGRAMMED BY: Faith Paule
COURSE: BCS35 | S-CSIS311LA
DUE DATE: Sept 23
TYPE: Class Participation

OBJECTIVES: Creating a comprehensive Machine Learning regression tutorial covering:
1. Simple Linear Regression with synthetic data (page speed vs purchase amount)
2. Understanding noise/variation effect on R-squared
3. Polynomial Regression (1st to 10th degree) with overfitting analysis
4. Multiple Linear Regression using car dataset (mileage, cylinder, liter, doors)
5. K-Fold Cross-Validation with SVM classifier on Iris dataset
6. SVM Kernel Comparison (linear, poly, rbf, sigmoid)

Programming Language: Python 3

Tech Stack:
- NumPy - Random data generation, numerical operations
- Matplotlib/Pylab - Data visualization, scatter plots, regression lines
- SciPy - Statistical linear regression (linregress)
- Scikit-learn (sklearn) - r2_score, cross_val_score, train_test_split, datasets (iris), SVM
- Pandas - Data manipulation, DataFrame for kernel comparison
- Statsmodels - OLS (Ordinary Least Squares) regression
- Google Colab - Jupyter notebook environment
"""

# ============================================================================
# SECTION 1: SIMPLE LINEAR REGRESSION
# ============================================================================

# %matplotlib inline
import numpy as np
from pylab import *

# Generate synthetic data: page speeds (normal distribution, mean=3.0, std=1.0, n=1000)
pageSpeeds = np.random.normal(3.0, 1.0, 1000)

# Purchase amount inversely related to page speed with noise
# Formula: 100 - (pageSpeed + noise) * 2
purchaseAmount = 100 - (pageSpeeds + np.random.normal(0, 0.1, 1000)) * 2

# Scatter plot to visualize relationship
scatter(pageSpeeds, purchaseAmount)
plt.title('Page Speed vs Purchase Amount')
plt.xlabel('Page Speed (seconds)')
plt.ylabel('Purchase Amount ($)')
plt.show()

# Perform linear regression using scipy
from scipy import stats
slope, intercept, r_value, p_value, std_err = stats.linregress(pageSpeeds, purchaseAmount)

# R-squared: Proportion of variance explained by the model (0-1, higher = better)
r_squared = r_value ** 2
print(f"R-squared: {r_squared:.4f}")

# Prediction function: y = mx + c
def predict(x):
    return slope * x + intercept

# Plot regression line over scatter plot
import matplotlib.pyplot as plt
fitline = predict(pageSpeeds)

plt.scatter(pageSpeeds, purchaseAmount)
plt.plot(pageSpeeds, fitline, c='r', label='Regression Line')
plt.title('Linear Regression Fit')
plt.xlabel('Page Speed')
plt.ylabel('Purchase Amount')
plt.legend()
plt.show()

"""
YOUR TURN: Increasing Variation
Try increasing the random variation in the test data, and see what effect 
it has on the r-squared error value.

OBSERVATION: Higher noise decreases R-squared because the model cannot 
explain the additional random variance in the data.
"""

# ============================================================================
# SECTION 2: INCREASED VARIATION (More Noise)
# ============================================================================

# Increase standard deviation from 0.1 to 2.0, and sample size to 2000
pageSpeeds = np.random.normal(3.0, 2.0, 2000)
purchaseAmount = 100 - (pageSpeeds + np.random.normal(0, 2.0, 2000)) * 2

# Perform linear regression on noisier data
slope, intercept, r_value, p_value, std_err = stats.linregress(pageSpeeds, purchaseAmount)

def predict(x):
    return slope * x + intercept

fitline = predict(pageSpeeds)

plt.scatter(pageSpeeds, purchaseAmount)
plt.plot(pageSpeeds, fitline, c='r')
plt.title('Linear Regression with Increased Noise')
plt.show()

r_squared_noisy = r_value ** 2
print(f"R-squared with increased noise: {r_squared_noisy:.4f}")
print("OBSERVATION: R-squared decreased due to higher random variation.")

# ============================================================================
# SECTION 3: POLYNOMIAL REGRESSION (Non-linear Data)
# ============================================================================

np.random.seed(2)
pageSpeeds = np.random.normal(3.0, 1.0, 1000)
# Non-linear relationship: purchaseAmount inversely proportional to pageSpeeds
purchaseAmount = np.random.normal(50.0, 10.0, 1000) / pageSpeeds

scatter(pageSpeeds, purchaseAmount)
plt.title('Non-linear Relationship: Page Speed vs Purchase Amount')
plt.show()

x = np.array(pageSpeeds)
y = np.array(purchaseAmount)

# 4th-degree polynomial fit
p4 = np.poly1d(np.polyfit(x, y, 4))
print(f"4th Degree Polynomial: {p4}")

xp = np.linspace(0, 7, 100)
plt.scatter(x, y)
plt.plot(xp, p4(xp), c='r', label='4th Degree Fit')
plt.legend()
plt.show()

from sklearn.metrics import r2_score
r2 = r2_score(y, p4(x))
print(f"R-squared (4th degree): {r2:.4f}")

"""
YOUR TURN: Polynomial Orders and Overfitting
Try different polynomial orders (1, 3, 4, 8). Higher orders may overfit.
"""

# ============================================================================
# SECTION 4: POLYNOMIAL COMPARISON (1st, 3rd, 4th, 8th Degree)
# ============================================================================

# 1st-degree (Linear)
p1 = np.poly1d(np.polyfit(x, y, 1))
r2_p1 = r2_score(y, p1(x))
print(f"1st-degree R-squared: {r2_p1:.4f}")

plt.scatter(x, y)
plt.plot(xp, p1(xp), c='r', label="1st Degree (Linear)")
plt.legend()
plt.show()

# 3rd-degree
p3 = np.poly1d(np.polyfit(x, y, 3))
r2_p3 = r2_score(y, p3(x))
print(f"3rd-degree R-squared: {r2_p3:.4f}")

plt.scatter(x, y)
plt.plot(xp, p3(xp), c='g', label="3rd Degree")
plt.legend()
plt.show()

# 4th-degree
p4 = np.poly1d(np.polyfit(x, y, 4))
r2_p4 = r2_score(y, p4(x))
print(f"4th-degree R-squared: {r2_p4:.4f}")

plt.scatter(x, y)
plt.plot(xp, p4(xp), c='orange', label="4th Degree")
plt.legend()
plt.show()

# 8th-degree (Higher risk of overfitting)
p8 = np.poly1d(np.polyfit(x, y, 8))
r2_p8 = r2_score(y, p8(x))
print(f"8th-degree R-squared: {r2_p8:.4f}")

plt.scatter(x, y)
plt.plot(xp, p8(xp), c='b', label="8th Degree")
plt.legend()
plt.show()

# ============================================================================
# SECTION 5: MULTIPLE LINEAR REGRESSION (Car Dataset)
# ============================================================================

import pandas as pd
df = pd.read_excel('cars.xls')

# Group mileage into bins and calculate average price
df1 = df[['Mileage', 'Price']]
bins = np.arange(0, 50000, 10000)
groups = df1.groupby(pd.cut(df1['Mileage'], bins)).mean()
print(groups.head())
groups['Price'].plot.line(title='Average Price by Mileage Range')
plt.show()

import statsmodels.api as sm
from sklearn.preprocessing import StandardScaler

# Features: Mileage, Cylinder, Liter, Doors
X = df[['Mileage', 'Cylinder', 'Liter', 'Doors']]
y = df['Price']

# Standardize features (mean=0, std=1) for coefficient comparison
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X[['Mileage', 'Cylinder', 'Liter', 'Doors']] = X_scaled

# Ordinary Least Squares regression
est = sm.OLS(y, X).fit()
print(est.summary())

# Average price by number of doors
print(y.groupby(df.Doors).mean())

# Predict price for a specific car (45,000 miles, 8 cylinders, 4 liters, 4 doors)
scaled = scaler.transform([[45000, 8, 4, 4]])
predicted = est.predict(scaled[0])
print(f"Predicted price: ${predicted[0]:,.2f}")

"""
YOUR TURN: Door Count Analysis
Create measurable influence of number of doors on price (2-10 doors).
"""

# ============================================================================
# SECTION 6: DOOR COUNT ANALYSIS (Synthetic Data)
# ============================================================================

np.random.seed(42)
n_samples = 1000

# Generate synthetic car data
mileage = np.random.randint(10000, 100000, n_samples)
cylinder = np.random.choice([4, 6, 8], n_samples)
liter = np.random.uniform(1.0, 5.0, n_samples)
doors = np.random.choice([2, 3, 4, 5, 6, 7, 8, 9, 10], n_samples)  # Expanded door range

# Price influenced by all features (doors contribute +$1,500 per door)
price = (20000 - mileage * 0.1 + cylinder * 1000 + liter * 3000 + doors * 1500 + 
         np.random.normal(0, 2000, n_samples))

car_data = pd.DataFrame({'Mileage': mileage, 'Price': price, 'Cylinder': cylinder, 
                         'Liter': liter, 'Doors': doors})

# Multiple regression
X = car_data[['Mileage', 'Cylinder', 'Liter', 'Doors']]
X_scaled = scaler.fit_transform(X)
X[['Mileage', 'Cylinder', 'Liter', 'Doors']] = X_scaled

est = sm.OLS(y, X).fit()
print(est.summary())

# Visualize door effect
door_effect = y.groupby(car_data.Doors).mean()
door_effect.plot(kind='bar', title='Average Price by Number of Doors')
plt.ylabel('Average Price')
plt.xlabel('Number of Doors')
plt.show()

# ============================================================================
# SECTION 7: K-FOLD CROSS-VALIDATION
# ============================================================================

np.random.seed(2)
pageSpeeds = np.random.normal(3.0, 1.0, 100)
purchaseAmount = np.random.normal(50.0, 30.0, 100) / pageSpeeds

# Split into train (80) and test (20)
trainX, testX = pageSpeeds[:80], pageSpeeds[80:]
trainY, testY = purchaseAmount[:80], purchaseAmount[80:]

# 8th-degree polynomial fit
p4 = np.poly1d(np.polyfit(trainX, trainY, 8))

# Evaluate on test data
r2_test = r2_score(testY, p4(testX))
r2_train = r2_score(trainY, p4(trainX))
print(f"Train R-squared: {r2_train:.4f}")
print(f"Test R-squared: {r2_test:.4f}")

# Find best polynomial degree (1-10) using test R-squared
degrees = range(1, 11)
r2_scores = []

for degree in degrees:
    p = np.poly1d(np.polyfit(trainX, trainY, degree))
    r2 = r2_score(testY, p(testX))
    r2_scores.append(r2)

best_degree = degrees[np.argmax(r2_scores)]
best_r2 = max(r2_scores)
print(f"Best degree: {best_degree}, R-squared: {best_r2:.4f}")

# ============================================================================
# SECTION 8: SVM KERNEL COMPARISON
# ============================================================================

from sklearn.model_selection import cross_val_score, train_test_split
from sklearn import datasets
from sklearn import svm

iris = datasets.load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.4, random_state=0)

# 5-Fold Cross-Validation with SVM
clf = svm.SVC(kernel='sigmoid', C=1).fit(X_train, y_train)
print(f"Test score (sigmoid): {clf.score(X_test, y_test):.4f}")

scores = cross_val_score(clf, iris.data, iris.target, cv=5)
print(f"5-Fold CV scores: {scores}")
print(f"Mean CV score: {scores.mean():.4f}")

# Compare different SVM kernels
kernels = ['linear', 'poly', 'rbf', 'sigmoid']
kernel_scores = []

for kernel in kernels:
    clf = svm.SVC(kernel=kernel, C=1).fit(X_train, y_train)
    score = clf.score(X_test, y_test)
    kernel_scores.append(score)

results = pd.DataFrame({'Kernel': kernels, 'Score': kernel_scores})
print(results)
best_kernel = results.loc[results['Score'].idxmax()]
print(f"Best kernel: {best_kernel['Kernel']} with score: {best_kernel['Score']:.4f}")
