# -*- coding: utf-8 -*-
"""Paule_Lab Activity 1: Modelling Introduction - Data Exploration

Automatically generated by Colab.

AUTHOR: Faith Paule
COURSE: BCS35
ACTIVITY: Machine Learning - Data Exploration (Iris Dataset), Data Visualization, Pre-Modeling Analysis

OBJECTIVES:
Exploratory Data Analysis (EDA) on the classic Iris dataset as an introductory machine learning activity. The tasks involve loading the data, exploring its structure (shape, missing values, statistics), and creating visualizations (histograms, pair plots, correlation heatmaps).
- Load a dataset and explore its structure
- Generate insights through statistics and visualizations
- Understand the importance of EDA before applying ML models

Language & Tech Stack
Programming Language: Python 3

Tech Stack:
- scikit-learn: Provides the Iris dataset (load_iris()).
- Pandas: For data manipulation (DataFrame) and summary statistics.
- Matplotlib & Seaborn: For data visualization (histograms, pair plots, heatmaps).
- Google Colab: The environment (as seen in the file path).
"""

# ============================================================================
# PART A – LOADING THE DATASET
# ============================================================================

from sklearn.datasets import load_iris
import pandas as pd

# Load the Iris dataset from scikit-learn
iris = load_iris()

# Create a Pandas DataFrame with feature columns
df = pd.DataFrame(iris.data, columns=iris.feature_names)

# Add the target (species) column
df["target"] = iris.target

# Display the first 5 rows to understand data structure
print("First 5 rows of the dataset:")
print(df.head())

"""
Part A Questions & Answers:
- How many features (columns) are there? → 4 features (sepal length, sepal width, petal length, petal width)
- What does the target column represent? → Species of iris flower (0=setosa, 1=versicolor, 2=virginica)
"""

# ============================================================================
# PART B – EXPLORING THE DATASET
# ============================================================================

print("\nDataset Shape (rows, columns):", df.shape)
print("\nMissing Values Per Column:")
print(df.isnull().sum())

print("\nSummary Statistics:")
print(df.describe())

"""
Part B Questions & Answers:
- How many samples (rows)? → 150
- Are there any missing values? → No, all columns have 0 missing values
- Which feature has the highest average value? → Petal length (~3.76)
"""

# ============================================================================
# PART C – VISUALIZING THE DATASET
# ============================================================================

import matplotlib.pyplot as plt
import seaborn as sns

# 1. Histograms: Feature distributions (range, spread, skewness)
df.hist(bins=20, figsize=(10, 6))
plt.suptitle("Feature Distributions (Histograms)", fontsize=14)
plt.show()

# 2. Pairplot: Feature relationships colored by species
sns.pairplot(df, hue="target", diag_kind="kde")
plt.suptitle("Pairplot of Iris Features", y=1.02)
plt.show()

# 3. Correlation Heatmap: Feature-to-feature relationships
corr = df.drop("target", axis=1).corr()
plt.figure(figsize=(6, 5))
sns.heatmap(corr, annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Correlation Heatmap (Excluding Target)")
plt.show()

"""
Part C Questions & Answers:
- Which feature seems to separate the species best?
    → Petal length and petal width clearly separate setosa from the other two species.
- Are any features strongly correlated?
    → Yes, petal length and petal width are highly correlated (~0.96). 
      Sepal length is also moderately correlated with petal features.
"""

# ============================================================================
# PART D – REFLECTION (Student's Written Summary)
# ============================================================================

reflection = """
What did you discover about the dataset?
    The Iris dataset contains 150 samples with 4 numerical features: sepal length/width 
    and petal length/width. The target has 3 classes (setosa, versicolor, virginica). 
    The data has no missing values, and the features are on similar scales.

Which features might be most useful for classification?
    Petal length and petal width are the most useful features because they show clear 
    separation between setosa and the other species. Setosa has much smaller petals.

Why is it important to explore data before applying ML models?
    Data exploration reveals patterns, outliers, correlations, and potential issues 
    like missing values. This understanding guides feature selection, model choice, 
    and preprocessing steps, ultimately leading to better model performance.
"""

print("\n" + "="*60)
print("PART D: STUDENT REFLECTION")
print("="*60)
print(reflection)
