# -*- coding: utf-8 -*-
"""K_Fold_CROSS_Validation - Polynomial Regression and Cross-Validation
Automatically generated by Colab.

AUTHOR: Faith Paule
DATE: 2025

IDENTIFICATION: Learning Cross-Validation techniques in Machine Learning, specifically:
- Polynomial Regression with train/test split (80/20) on synthetic data
- K-Fold Cross-Validation (cv=5) using SVM classifier on the Iris dataset
- Comparing model performance across different polynomial degrees

Programming Language: Python 3

TOPIC: Machine Learning - Cross-Validation Techniques
- Train/Test Split
- Polynomial Regression
- K-Fold Cross-Validation (cv=5)
- SVM Classifier on Iris Dataset

Tech Stack:
- NumPy - Numerical operations, random data generation
- Matplotlib/Pylab - Data visualization
- Scikit-learn (sklearn) - train_test_split, cross_val_score, SVM, metrics (r2_score), datasets (iris)
- Google Colab - Jupyter notebook environment
"""

# ============================================================================
# PART 1: SYNTHETIC DATA GENERATION (Non-linear relationship)
# ============================================================================

# %matplotlib inline
import numpy as np
from pylab import *

np.random.seed(2)  # For reproducibility

# Generate synthetic data: page speeds (normal distribution)
pageSpeeds = np.random.normal(3.0, 1.0, 100)

# Purchase amount inversely proportional to page speed (non-linear)
purchaseAmount = np.random.normal(50.0, 30.0, 100) / pageSpeeds

# Scatter plot to visualize relationship
scatter(pageSpeeds, purchaseAmount)
plt.title('Page Speed vs Purchase Amount (Non-linear)')
plt.xlabel('Page Speed (seconds)')
plt.ylabel('Purchase Amount ($)')
plt.show()

# ============================================================================
# PART 2: TRAIN/TEST SPLIT (80/20)
# ============================================================================

# Split data: first 80 for training, last 20 for testing
trainX = pageSpeeds[:80]
testX = pageSpeeds[80:]

trainY = purchaseAmount[:80]
testY = purchaseAmount[80:]

# Visualize training data
scatter(trainX, trainY)
plt.title('Training Data (80 samples)')
plt.xlabel('Page Speed')
plt.ylabel('Purchase Amount')
plt.show()

# Visualize test data
scatter(testX, testY)
plt.title('Test Data (20 samples)')
plt.xlabel('Page Speed')
plt.ylabel('Purchase Amount')
plt.show()

# ============================================================================
# PART 3: POLYNOMIAL REGRESSION (Degree 8)
# ============================================================================

x = np.array(trainX)
y = np.array(trainY)

# Fit 8th degree polynomial to training data
p4 = np.poly1d(np.polyfit(x, y, 8))

import matplotlib.pyplot as plt

# Generate smooth x values for plotting
xp = np.linspace(0, 7, 100)

# Plot training data and polynomial fit
axes = plt.axes()
axes.set_xlim([0, 7])
axes.set_ylim([0, 200])
plt.scatter(x, y)
plt.plot(xp, p4(xp), c='r')
plt.title('Polynomial Regression (Degree 8) on Training Data')
plt.xlabel('Page Speed')
plt.ylabel('Purchase Amount')
plt.show()

# ============================================================================
# PART 4: EVALUATE ON TEST DATA
# ============================================================================

testx = np.array(testX)
testy = np.array(testY)

# Plot test data with the same polynomial model
axes = plt.axes()
axes.set_xlim([0, 7])
axes.set_ylim([0, 200])
plt.scatter(x, y)
plt.plot(xp, p4(xp), c='r')
plt.title('Same Model Applied to Test Data')
plt.xlabel('Page Speed')
plt.ylabel('Purchase Amount')
plt.show()

from sklearn.metrics import r2_score

# Calculate R² on test data (how well model generalizes)
r2_test = r2_score(testy, p4(testx))
print(f"R-squared on TEST data: {r2_test}")

# Calculate R² on training data (how well model fits)
r2_train = r2_score(np.array(trainY), p4(np.array(trainX)))
print(f"R-squared on TRAIN data: {r2_train}")

"""
YOUR TURN:
Try measuring the error on the test data using different degree polynomial fits.
What degree works best?

OBSERVATION:
- Lower degrees (1-3): Underfitting - high bias, low R² on both train and test
- Medium degrees (4-6): Good balance - best generalization
- Higher degrees (7+): Overfitting - high R² on train, low R² on test
"""

# ============================================================================
# PART 5: K-FOLD CROSS-VALIDATION WITH SVM ON IRIS DATASET
# ============================================================================

import numpy as np
from sklearn.model_selection import cross_val_score, train_test_split
from sklearn import datasets
from sklearn import svm

# Load the classic Iris dataset (150 samples, 3 classes)
iris = datasets.load_iris()

# Regular train/test split (60/40)
X_train, X_test, y_train, y_test = train_test_split(
    iris.data, iris.target, test_size=0.4, random_state=0
)

# Train SVM classifier with sigmoid kernel
clf = svm.SVC(kernel='sigmoid', C=1).fit(X_train, y_train)

# Evaluate on test set
test_score = clf.score(X_test, y_test)
print(f"\nSingle Train/Test Split Score: {test_score}")

# ============================================================================
# K-FOLD CROSS-VALIDATION (5 folds)
# ============================================================================

"""
K-Fold Cross-Validation (cv=5):
- Splits data into 5 equal parts (folds)
- Trains on 4 folds, tests on 1 fold
- Repeats 5 times, each fold used as test once
- Returns array of 5 scores
"""

scores = cross_val_score(clf, iris.data, iris.target, cv=5)

print(f"\n5-Fold Cross-Validation Scores: {scores}")
print(f"Mean Cross-Validation Score: {scores.mean():.4f}")
print(f"Standard Deviation: {scores.std():.4f}")
