# -*- coding: utf-8 -*-
"""CSIS311_ElbowMethod_110424 - K-Means Clustering with Elbow Method

Automatically generated by Colab.

AUTHOR: Faith Paule
DATE: 

PROGRAM: K-Means Clustering - Elbow Method for Optimal Clusters
TOPIC: Machine Learning (ML) - Unsupervised Learning, Clustering, K-Means, Elbow Method
OBJECTIVE: Determine optimal number of clusters using WCSS (Within-Cluster Sum of Squares)

IDENTIFICATION: Implementing K-Means Clustering with the Elbow Method to determine the optimal number of clusters. The code:
- Loads the Iris dataset (4 features: sepal length/width, petal length/width)
- Uses the Elbow Method (WCSS - Within-Cluster Sum of Squares) to find optimal k
- Clusters data into 3 groups (matching Iris flower species)
- Visualizes clusters with centroids
- Creates synthetic customer data (income + age) and applies K-Means clustering

Programming Language: Python 3

Tech Stack:
- Scikit-learn (sklearn) - KMeans, datasets (iris)
- NumPy - Numerical operations, random data generation
- Pandas - DataFrame manipulation
- Matplotlib - Visualization (scatter plots, elbow curve)
- Google Colab - Jupyter notebook environment
"""

# ============================================================================
# PART 1: LOAD AND EXPLORE IRIS DATASET
# ============================================================================
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets

# Load Iris dataset (150 samples, 4 features)
iris = datasets.load_iris()
iris_df = pd.DataFrame(iris.data, columns=iris.feature_names)
iris_df['target'] = iris.target  # Add target column (species)
iris_df.head()  # Display first 5 rows

# Extract feature values (all 4 numeric columns)
x = iris_df.iloc[:, [0, 1, 2, 3]].values

# ============================================================================
# PART 2: ELBOW METHOD - FIND OPTIMAL NUMBER OF CLUSTERS
# ============================================================================
from sklearn.cluster import KMeans

# Calculate WCSS (Within-Cluster Sum of Squares) for k = 1 to 10
wcss = []
for i in range(1, 11):
    kmeans = KMeans(n_clusters=i, random_state=42)
    kmeans.fit(x)
    wcss.append(kmeans.inertia_)  # inertia_ = WCSS

# Plot elbow curve
plt.plot(range(1, 11), wcss, marker='o')
plt.title('The Elbow Method for Optimal k')
plt.xlabel('Number of Clusters (k)')
plt.ylabel('WCSS (Within-Cluster Sum of Squares)')
plt.grid(True)
plt.show()
# OBSERVATION: Elbow appears at k=3 (optimal number of clusters)

# ============================================================================
# PART 3: TRAIN K-MEANS WITH OPTIMAL K=3
# ============================================================================
# Create and train K-Means model with 3 clusters
kmeans = KMeans(n_clusters=3, random_state=42)
kmeans_model = kmeans.fit(x)

# Predict cluster for each data point
y_kmeans = kmeans_model.predict(x)

# ============================================================================
# PART 4: VISUALIZE CLUSTERS AND CENTROIDS
# ============================================================================
plt.figure(figsize=(15, 6))

# Plot clusters (using Sepal Length vs Sepal Width for visualization)
plt.scatter(x[y_kmeans == 0, 0], x[y_kmeans == 0, 1], s=100, c='red', label='Cluster 0')
plt.scatter(x[y_kmeans == 1, 0], x[y_kmeans == 1, 1], s=100, c='blue', label='Cluster 1')
plt.scatter(x[y_kmeans == 2, 0], x[y_kmeans == 2, 1], s=100, c='green', label='Cluster 2')

# Plot cluster centroids
plt.scatter(kmeans.cluster_centers_[:, 0], kmeans.cluster_centers_[:, 1], 
            s=200, c='yellow', marker='X', label='Centroids', edgecolors='black')

plt.xlabel('Sepal Length (cm)')
plt.ylabel('Sepal Width (cm)')
plt.title('K-Means Clustering of Iris Dataset (k=3)')
plt.legend()
plt.show()

# ============================================================================
# PART 5: PREDICT CLUSTER FOR NEW DATA POINT
# ============================================================================
# Predict which cluster a new flower belongs to
new_flower = [[1.2, 3.4, 5.5, 6.7]]
predicted_cluster = kmeans_model.predict(new_flower)[0]
print(f"New flower (sepal length=1.2, sepal width=3.4, petal length=5.5, petal width=6.7)")
print(f"Assigned to cluster: {predicted_cluster}")

# ============================================================================
# CHALLENGE: SYNTHETIC CUSTOMER DATA CLUSTERING
# ============================================================================
"""
Create synthetic customer data with two features:
- Income (centroids between $20,000 and $200,000)
- Age (centroids between 20 and 70 years)
Use K-Means to identify customer segments
"""

from numpy import random, array

def createClusteredData(N, k):
    """
    Generate synthetic clustered data with k clusters.
    
    Args:
        N: Total number of data points
        k: Number of clusters
    
    Returns:
        X: Array of shape (N, 2) with [income, age] pairs
    """
    random.seed(10)
    pointsPerCluster = float(N) / k
    X = []
    
    for i in range(k):
        # Random centroids for income and age
        incomeCentroid = random.uniform(20000.0, 200000.0)
        ageCentroid = random.uniform(20.0, 70.0)
        
        # Generate points around centroids with normal distribution
        for j in range(int(pointsPerCluster)):
            X.append([
                random.normal(incomeCentroid, 10000.0),  # Income with std 10,000
                random.normal(ageCentroid, 2.0)         # Age with std 2
            ])
    
    return array(X)


# Generate synthetic customer data (100 points, 5 clusters)
data = createClusteredData(100, 5)

# Scale the data for better clustering
from sklearn.preprocessing import scale

# Apply K-Means with 5 clusters
model = KMeans(n_clusters=5, random_state=42)
model = model.fit(scale(data))

print("Cluster labels for each customer:")
print(model.labels_)

# Visualize customer segments
plt.figure(figsize=(8, 6))
plt.scatter(data[:, 0], data[:, 1], c=model.labels_.astype(float), cmap='viridis')
plt.scatter(model.cluster_centers_[:, 0], model.cluster_centers_[:, 1], 
            s=200, c='red', marker='X', label='Centroids')
plt.xlabel('Annual Income ($)')
plt.ylabel('Age (years)')
plt.title('Customer Segmentation using K-Means Clustering (k=5)')
plt.colorbar(label='Cluster')
plt.legend()
plt.show()

# Additional prediction example
print(f"\nPrediction for new flower (same as above): {predicted_cluster}")
