# -*- coding: utf-8 -*-
"""Paule_CSIS311_KNN - K-Nearest Neighbors Classification

Automatically generated by Colab.

PROGRAM: K-Nearest Neighbors (K-NN) Classifier
AUTHOR: Faith Paule
COURSE: CSIS311
TOPIC: Machine Learning - Classification
DATE: 2025

OBJECTIVE: Predict whether a user will purchase a product based on:
- Age
- Estimated Salary

IDENTIFICATION: Implementing a K-Nearest Neighbors (K-NN) classifier for a social network ad purchase prediction problem. The complete ML pipeline includes: data loading, feature scaling, train/test split, model training, prediction, evaluation metrics (confusion matrix, accuracy, precision, recall, F1-score), and decision boundary visualization.

Topic: Machine Learning (ML) - Supervised Learning, Classification, K-Nearest Neighbors (K-NN)

Programming Language: Python 3

Tech Stack:
- Pandas - Data loading and manipulation
- NumPy - Numerical operations, array reshaping
- Matplotlib - Decision boundary visualization
- Scikit-learn (sklearn) - train_test_split, StandardScaler, KNeighborsClassifier, confusion_matrix, accuracy_score, precision_score, recall_score, f1_score, classification_report
- Google Colab - Jupyter notebook environment
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# ============================================================================
# STEP 1: LOAD DATASET
# ============================================================================
# Dataset contains: Age, Estimated Salary, Purchased (0 = No, 1 = Yes)
dataset = pd.read_csv('Social_Network_Ads-1.csv')

# Features (Age, Estimated Salary)
X = dataset.iloc[:, :-1].values

# Target (Purchased)
y = dataset.iloc[:, -1].values

# ============================================================================
# STEP 2: TRAIN/TEST SPLIT (75% Train, 25% Test)
# ============================================================================
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

print("Training Features:\n", X_train)
print("\nTraining Labels:\n", y_train)
print("\nTesting Features:\n", X_test)
print("\nTesting Labels:\n", y_test)

# ============================================================================
# STEP 3: FEATURE SCALING (Standardization)
# ============================================================================
# Important for distance-based algorithms like K-NN
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

# Fit scaler on training data, then transform both train and test
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

print("\nScaled Training Features:\n", X_train)
print("\nScaled Testing Features:\n", X_test)

# ============================================================================
# STEP 4: TRAIN K-NN CLASSIFIER
# ============================================================================
from sklearn.neighbors import KNeighborsClassifier

# n_neighbors = 5 (default, considers 5 nearest neighbors)
# metric = 'minkowski', p = 2 → Euclidean distance
classifier = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2)
classifier.fit(X_train, y_train)

# ============================================================================
# STEP 5: MAKE PREDICTIONS
# ============================================================================
# Predict for a 30-year-old with $87,000 salary
# Note: Must scale input using the same scaler
prediction = classifier.predict(sc.transform([[30, 87000]]))
print(f"\nPrediction for Age=30, Salary=87,000: {'Purchase' if prediction[0] == 1 else 'No Purchase'}")

# Predict on entire test set
y_pred = classifier.predict(X_test)

# Compare predictions with actual values
print("\nPredicted vs Actual (side by side):")
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

# ============================================================================
# STEP 6: EVALUATION METRICS
# ============================================================================
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score, classification_report

# Confusion Matrix
# [[TN, FP],
#  [FN, TP]]
cm = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:")
print(cm)

print(f"\nAccuracy: {accuracy_score(y_test, y_pred):.4f}")
print(f"Precision: {precision_score(y_test, y_pred):.4f}")
print(f"Recall: {recall_score(y_test, y_pred):.4f}")
print(f"F1-Score: {f1_score(y_test, y_pred):.4f}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# ============================================================================
# STEP 7: VISUALIZE DECISION BOUNDARIES
# ============================================================================
from matplotlib.colors import ListedColormap

def plot_decision_boundary(X_set, y_set, title, scaler=None):
    """
    Plot K-NN decision boundaries for training or test set.
    
    Parameters:
    X_set: Features (scaled)
    y_set: Labels
    title: Plot title
    scaler: Original scaler (for inverse transform)
    """
    # Create mesh grid
    X1, X2 = np.meshgrid(
        np.arange(start=X_set[:, 0].min() - 1, stop=X_set[:, 0].max() + 1, step=0.01),
        np.arange(start=X_set[:, 1].min() - 1, stop=X_set[:, 1].max() + 1, step=0.01)
    )
    
    # Predict on mesh grid points
    Z = classifier.predict(np.array([X1.ravel(), X2.ravel()]).T)
    Z = Z.reshape(X1.shape)
    
    # Plot decision regions
    plt.contourf(X1, X2, Z, alpha=0.75, cmap=ListedColormap(('purple', 'yellow')))
    plt.xlim(X1.min(), X1.max())
    plt.ylim(X2.min(), X2.max())
    
    # Plot data points
    for i, j in enumerate(np.unique(y_set)):
        plt.scatter(X_set[y_set == j, 0], X_set[y_set == j, 1],
                   c=ListedColormap(('purple', 'gold'))(i), label=j)
    
    plt.title(title)
    plt.xlabel('Age (scaled)')
    plt.ylabel('Estimated Salary (scaled)')
    plt.legend()
    plt.show()

# Plot training set decision boundaries
plot_decision_boundary(X_train, y_train, 'K-NN (Training set)')

# Plot test set decision boundaries
plot_decision_boundary(X_test, y_test, 'K-NN (Test set)')
