# -*- coding: utf-8 -*-
"""Regression2 - Linear, Polynomial, and Multiple Regression Tutorial
AUTHOR: Faith Paule
DATE: 2025

IDENTIFICATION: Building a Linear Regression model to predict Median House Value based on Median Income using the California Housing dataset, with comprehensive exploratory data analysis (EDA), data visualization, outlier removal, and model evaluation.

Topic: Machine Learning (ML) - Supervised Learning, Linear Regression, Regression Analysis

Programming Language: Python 3

Tech Stack:
- NumPy - Numerical operations
- Pandas - Data manipulation and analysis
- Matplotlib - Data visualization
- Seaborn - Statistical data visualization
- Scikit-learn (sklearn) - Machine learning model (LinearRegression, train_test_split, metrics)
- Google Colab - Jupyter notebook environment

Automatically generated by Colab.

TOPIC: Machine Learning - Regression Analysis
- Simple Linear Regression
- Polynomial Regression
- Multiple Linear Regression
"""

# ============================================================================
# PART 1: SIMPLE LINEAR REGRESSION WITH SYNTHETIC DATA
# ============================================================================

# %matplotlib inline
import numpy as np
from pylab import *

# Generate synthetic data: page speeds (normal distribution, mean=3.0, std=1.0, n=1000)
pageSpeeds = np.random.normal(3.0, 1.0, 1000)

# Purchase amount inversely related to page speed with some noise
purchaseAmount = 100 - (pageSpeeds + np.random.normal(0, 0.1, 1000)) * 2

# Scatter plot to visualize relationship
scatter(pageSpeeds, purchaseAmount)

# Perform linear regression using scipy
from scipy import stats
slope, intercept, r_value, p_value, std_err = stats.linregress(pageSpeeds, purchaseAmount)

# Calculate R-squared (coefficient of determination)
r_squared = r_value ** 2
print(f"R-squared: {r_squared}")

# Create prediction function
import matplotlib.pyplot as plt

def predict(x):
    return slope * x + intercept

fitLine = predict(pageSpeeds)

# Plot regression line
plt.scatter(pageSpeeds, purchaseAmount)
plt.plot(pageSpeeds, fitLine, c='r')
plt.title('Linear Regression: Page Speed vs Purchase Amount')
plt.xlabel('Page Speed (seconds)')
plt.ylabel('Purchase Amount ($)')
plt.show()

"""
YOUR TURN:
Try increasing the random variation in the test data, and see what effect it 
has on the r-squared error value. Explain your observation and interpretation.

OBSERVATION: Increasing random variation (noise) decreases R-squared because 
the linear model cannot explain the additional variance in the data.
"""

# ============================================================================
# PART 2: POLYNOMIAL REGRESSION (Non-linear relationships)
# ============================================================================

# %matplotlib inline
import numpy as np
from pylab import *

np.random.seed(2)  # For reproducibility

# Generate non-linear data: purchaseAmount inversely proportional to pageSpeeds
pageSpeeds = np.random.normal(3.0, 1.0, 1000)
purchaseAmount = np.random.normal(50.0, 10.0, 1000) / pageSpeeds

scatter(pageSpeeds, purchaseAmount)
plt.title('Non-linear Relationship: Page Speed vs Purchase Amount')
plt.xlabel('Page Speed (seconds)')
plt.ylabel('Purchase Amount ($)')
plt.show()

# Fit polynomial regression (4th degree)
x = np.array(pageSpeeds)
y = np.array(purchaseAmount)

# polyfit returns coefficients, poly1d creates polynomial function
p4 = np.poly1d(np.polyfit(x, y, 4))
print(f"4th Degree Polynomial:\n{p4}")

# Visualize polynomial fit
xp = np.linspace(0, 7, 100)
plt.scatter(x, y)
plt.plot(xp, p4(xp), c='r')
plt.title('Polynomial Regression (4th Degree)')
plt.xlabel('Page Speed (seconds)')
plt.ylabel('Purchase Amount ($)')
plt.show()

# Calculate R-squared for polynomial model
from sklearn.metrics import r2_score
r2 = r2_score(y, p4(x))
print(f"R-squared (4th degree): {r2}")

"""
YOUR TURN:
Try different polynomial orders. Can you get a better fit with higher orders?
- 1st degree: p1 = np.poly1d(np.polyfit(x, y, 1))
- 3rd degree: p3 = np.poly1d(np.polyfit(x, y, 3))
- 8th degree: p8 = np.poly1d(np.polyfit(x, y, 8))

INTERPRETATION: Higher degree polynomials may fit training data better (higher R-squared)
but can lead to overfitting - capturing noise instead of the underlying pattern.
"""

# ============================================================================
# PART 3: MULTIPLE LINEAR REGRESSION (Car Dataset)
# ============================================================================

import pandas as pd
df = pd.read_excel('cars.xls')

# %matplotlib inline
import numpy as np

# Select Mileage and Price columns, group by mileage bins
df1 = df[['Mileage', 'Price']]
bins = np.arange(0, 50000, 10000)
groups = df1.groupby(pd.cut(df1['Mileage'], bins)).mean()
print(groups.head())

# Plot average price by mileage group
groups['Price'].plot.line()
plt.title('Average Price by Mileage Range')
plt.xlabel('Mileage Range')
plt.ylabel('Average Price ($)')
plt.show()

# ============================================================================
# MULTIPLE REGRESSION WITH FEATURE SCALING
# ============================================================================

import statsmodels.api as sm
from sklearn.preprocessing import StandardScaler

# Features: Mileage, Cylinder, Liter, Doors
# Target: Price
X = df[['Mileage', 'Cylinder', 'Liter', 'Doors']]
y = df['Price']

# Scale features to same range for coefficient comparison
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Convert back to DataFrame with same column names
X[['Mileage', 'Cylinder', 'Liter', 'Doors']] = X_scaled

print(X.head())

# Ordinary Least Squares regression
est = sm.OLS(y, X).fit()
print(est.summary())

# Group average price by number of doors
print(y.groupby(df.Doors).mean())

# Predict price for a specific car
# 45000 miles, 8 cylinders, 4 liters, 4 doors
scaled = scaler.transform([[45000, 8, 4, 4]])
print(f"Scaled features: {scaled}")

predicted_price = est.predict(scaled[0])
print(f"Predicted price: ${predicted_price[0]:,.2f}")

"""
YOUR TURN:
Mess around with the sample input data, and see if you can create a measurable 
influence of number of doors on price. Try 5, 7, 8, 10 doors.

INTERPRETATION: Number of doors may have a non-linear relationship with price.
Luxury cars might have fewer doors (coupes) or more (SUVs/vans), affecting price.
"""
