# -*- coding: utf-8 -*-
"""Paule_Regression - Linear Regression for House Price Prediction

Automatically generated by Colab.

PROGRAM: Linear Regression - House Value Prediction
AUTHOR: Faith Paule
COURSE: BCS35 / S-CSIS311LA
DATE: Due Sep 19

OBJECTIVE: Predict Median House Value based on Median Income
ALGORITHM: Linear Regression (y = mx + c)

Building a Linear Regression model to predict Median House Value based on Median Income using the California Housing dataset, with comprehensive exploratory data analysis (EDA), data visualization, outlier removal, and model evaluation.

Topic: Machine Learning (ML) - Supervised Learning, Linear Regression, Regression Analysis

Programming Language: Python 3

Tech Stack:
- NumPy - Numerical operations
- Pandas - Data manipulation and analysis
- Matplotlib - Data visualization
- Seaborn - Statistical data visualization
- Scikit-learn (sklearn) - Machine learning model (LinearRegression, train_test_split, metrics)
- Google Colab - Jupyter notebook environment
"""

# ============================================================================
# PROGRAM HEADER
# ============================================================================
# Programmed by: Faith Paule
# BCS35
# Due: Sep 19
# S-CSIS311LA
# Using Anaconda or Google Colab, solve the machine problem.
# Evaluate, analyze, and explain the steps using your chosen tool.
# Use the dataset housing. After completing the solution, create two copies: 
# one in PDF format and one in Python (.py) format.

# ============================================================================
# STEP 1: IMPORT LIBRARIES
# ============================================================================
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score

# Set random seed for reproducibility
SEED = 42
np.random.seed(SEED)

# ============================================================================
# STEP 2: LOAD AND EXPLORE DATA
# ============================================================================
# Load the dataset
df = pd.read_csv('housing.csv')
print(df.head())

# Display basic info
print(df.head())
print(df.info())

# Select only the columns needed for regression
df = df[['median_income', 'median_house_value']]

# Display dataframe information
print(df.info())
print('')
print(df.head(10))

# ============================================================================
# STEP 3: EXPLORATORY DATA ANALYSIS (EDA)
# ============================================================================
# Summary statistics
print(df.describe())

"""
QUESTION 5: What values do you see?
ANSWER: The summary statistics for numerical columns: count, mean, standard deviation, 
min, max, and quartiles. These show the overall distribution and range of the data.
"""

# Distribution of Median Income
plt.figure(figsize=(12, 6))
plt.subplot(1, 2, 1)
sns.histplot(df['median_income'], kde=True)
plt.title('Distribution of Median Income')

"""
QUESTION 6: What distributions do you see?
ANSWER: Most households have lower to mid-range incomes, with fewer households 
having very high incomes (right-skewed distribution).
"""

# Relationship between variables
plt.figure(figsize=(8, 6))
sns.scatterplot(x='median_income', y='median_house_value', data=df)
plt.title('Relationship between Median Income and Median House Value')
plt.show()

"""
QUESTION 7: What relationships do you see?
ANSWER: There is a positive correlation - people with higher income tend to have 
more expensive houses.

QUESTION 8: What relationships might benefit the prediction problem?
ANSWER: The correlation between median income and house value is key. Higher income 
areas have higher property values, making linear regression an appropriate model.

QUESTION 9: What ideas about the domain does the data spark?
ANSWER: Housing value is tightly linked to income levels. Income inequality may be 
a driving factor in the housing market.
"""

# Display column info
print(df.columns)
print(df.head())
print(df.tail())
print(df.info())

# Summary statistics
print(df.describe())

# Check for missing values
df_na = df.isna().sum()
print(df_na)

# Categorical data (if any)
df_cat = df.select_dtypes(include=['object'])
print(df_cat.nunique())

# Numerical data
df_num = df.select_dtypes(include=['number'])
print(df_num.nunique())

# Correlation matrix
print(df_num.corr())

# Group and sort data
print(df.groupby(by='median_house_value').count().sort_values('median_house_value', ascending=False).head(10))

# ============================================================================
# STEP 4: DATA VISUALIZATION
# ============================================================================
# Scatter plot
df.plot.scatter('median_income', 'median_house_value')

# Boxplot
sns.boxplot(y='median_house_value', data=df)

# Violin plot
sns.violinplot(y='median_house_value', data=df)

# Joint plot with regression line
sns.jointplot(x="median_income", y="median_house_value", data=df, kind="reg")

# ============================================================================
# STEP 5: REMOVE OUTLIERS
# ============================================================================
# Remove houses with value > $500,000 to improve model performance
df.drop(df[df['median_house_value'] > 500000].index, inplace=True)

# Verify outlier removal
_ = sns.violinplot(y='median_house_value', data=df)
_ = sns.jointplot(x="median_income", y="median_house_value", data=df, kind="reg")

# ============================================================================
# STEP 6: PREPARE DATA FOR TRAINING AND TESTING
# ============================================================================
# Separate independent (X) and dependent (y) variables
x = df.iloc[:, 0].values.reshape(-1, 1)  # median_income (input/feature)
y = df.iloc[:, 1].values                  # median_house_value (target)

# Split data into training (80%) and testing (20%) sets
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, shuffle=False, random_state=SEED)

# ============================================================================
# STEP 7: TRAIN THE LINEAR REGRESSION MODEL
# ============================================================================
from sklearn.linear_model import LinearRegression

# Create and train the regressor
regressor = LinearRegression()
regressor.fit(x_train, y_train)

# ============================================================================
# STEP 8: VISUALIZE THE TRAINED MODEL
# ============================================================================
# Linear Regression equation: y = m*x + c
# where m = coefficient (slope), c = intercept
line = regressor.coef_ * x + regressor.intercept_

# Plot the regression line on scatter plot
plt.scatter(x, y)
plt.plot(x, line, 'r')
plt.xlabel('Median House Value')
plt.ylabel('Median Income')
plt.title('Median House Value vs Median Income')
plt.show()
