# -*- coding: utf-8 -*-
"""Paule_CSIS311LA_SVM - Face Recognition with Support Vector Machines

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ryCTtU6CNVVlNlEY4fN8Q2CoKHABidli

PROGRAM: SVM Face Recognition
AUTHOR: Faith Paule
COURSE: CSIS311LA
TOPIC: Machine Learning - Computer Vision, Image Classification, Support Vector Machines (SVM), Face Recognition

Programming Language: Python 3

Tech Stack:
- Scikit-learn (sklearn) - fetch_lfw_people dataset, train_test_split, SVC, classification_report, confusion_matrix
- Matplotlib - Image display, subplot visualization, confusion matrix heatmap
- Seaborn - Enhanced confusion matrix visualization
- NumPy - Array operations, unique value counting
- Pandas - Synthetic fruit dataset creation
- Google Colab - Jupyter notebook environment

IDENTIFICATION Building a Face Recognition system using Support Vector Machine (SVM) on the Labeled Faces in the Wild (LFW) dataset
OBJECTIVES:
1. Load and visualize Labeled Faces in the Wild (LFW) dataset
2. Train SVM classifier with RBF kernel for face recognition
3. Evaluate model performance with classification report
4. Visualize predictions (correct in black, incorrect in red)
5. Display confusion matrix heatmap
6. Create SVM fruit classifier as seatwork
"""

# ============================================================================
# PART 1: LOAD LABELED FACES IN THE WILD (LFW) DATASET
# ============================================================================
from sklearn.datasets import fetch_lfw_people
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load dataset: only include people with at least 100 face images
faces = fetch_lfw_people(min_faces_per_person=100)

# Display target names (people's names) and dataset shape
print("Target Names (People):", faces.target_names)
print(f"Images shape: {faces.images.shape}")  # (samples, height, width)

# ============================================================================
# PART 2: VISUALIZE FACE IMAGES
# ============================================================================
# Create a 1x3 grid of sample images
fig, ax = plt.subplots(1, 3)
for i, axi in enumerate(ax.flat):
    axi.imshow(faces.images[i], cmap='bone')
    axi.set(xticks=[], yticks=[])
    axi.set_xlabel(faces.target_names[faces.target[i]])

plt.suptitle('Sample Face Images')
plt.show()

# Create a 3x5 grid for more sample images
fig, ax = plt.subplots(3, 5)
fig = plt.gcf()  # Get current figure
fig.set_size_inches(9, 6)
for i, axi in enumerate(ax.flat):
    axi.imshow(faces.images[i], cmap='gray')
    axi.set(xticks=[], yticks=[])
    axi.set_xlabel(faces.target_names[faces.target[i]])

plt.suptitle('Face Images Grid (3x5)')
plt.show()

# ============================================================================
# PART 3: TRAIN/TEST SPLIT AND SVM MODEL TRAINING
# ============================================================================
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

# Split data: 75% train, 25% test (default)
X_train, X_test, y_train, y_test = train_test_split(
    faces.data, faces.target, random_state=42
)

# Initialize SVM with RBF kernel (Radial Basis Function)
# class_weight='balanced' adjusts weights inversely to class frequency
model = SVC(kernel='rbf', class_weight='balanced')
model.fit(X_train, y_train)

# ============================================================================
# PART 4: MAKE PREDICTIONS AND VISUALIZE RESULTS
# ============================================================================
yfit = model.predict(X_test)

# Create 4x6 grid showing predictions (correct in black, incorrect in red)
fig, ax = plt.subplots(4, 6)
fig = plt.gcf()
fig.set_size_inches(11, 8)

for i, axi in enumerate(ax.flat):
    if i < len(X_test):  # Ensure we don't exceed available images
        axi.imshow(X_test[i].reshape(62, 47), cmap='gray')
        axi.set(xticks=[], yticks=[])
        # Black text for correct predictions, red for incorrect
        axi.set_ylabel(faces.target_names[yfit[i]],
                       color='black' if yfit[i] == y_test[i] else 'red')

fig.suptitle('Predicted Names; Incorrect Labels in Red', size=14)
plt.tight_layout()
plt.show()

# ============================================================================
# PART 5: EVALUATION METRICS
# ============================================================================
from sklearn.metrics import classification_report

print("\nClassification Report:")
print(classification_report(y_test, yfit, target_names=faces.target_names))

# ============================================================================
# PART 6: CLASS DISTRIBUTION ANALYSIS
# ============================================================================
# Count occurrences of each person in the dataset
unique, counts = np.unique(faces.target, return_counts=True)
occurrences = dict(zip(faces.target_names[unique], counts))

print("\nClass Distribution (Number of images per person):")
for name, count in occurrences.items():
    print(f"  {name}: {count} images")

# ============================================================================
# PART 7: CONFUSION MATRIX VISUALIZATION
# ============================================================================
from sklearn.metrics import confusion_matrix

# Compute confusion matrix
conf_mat = confusion_matrix(y_test, yfit)

# Plot heatmap for better interpretation
plt.figure(figsize=(10, 8))
sns.heatmap(conf_mat, annot=True, fmt='d', cbar=True,
            xticklabels=faces.target_names,
            yticklabels=faces.target_names)
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix - Face Recognition')
plt.show()

# ============================================================================
# SEATWORK: FRUIT CLASSIFICATION WITH SVM
# Create a different SVM using Fruits dataset
# ============================================================================
print("\n" + "="*60)
print("SEATWORK: Fruit Classification with SVM")
print("="*60)

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

# Step 1: Create a synthetic fruits dataset
# Features: Weight (grams), Sweetness (scale 1-10)
data = {
    'Weight': [150, 120, 130, 170, 200, 180, 160, 140, 90, 110],
    'Sweetness': [7, 8, 5, 9, 6, 5, 4, 8, 3, 2],
    'Fruit': ['Apple', 'Apple', 'Banana', 'Banana', 'Orange',
              'Orange', 'Grapes', 'Grapes', 'Strawberry', 'Strawberry']
}

# Create DataFrame
fruits = pd.DataFrame(data)
print("\nFruits Dataset:")
print(fruits)

# Step 2: Prepare features and labels
X = fruits[['Weight', 'Sweetness']].values  # Features
y = fruits['Fruit'].values                   # Labels

# Step 3: Split into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

print(f"\nTraining set size: {len(X_train)}")
print(f"Testing set size: {len(X_test)}")

# Step 4: Train SVM model
fruit_model = SVC(kernel='rbf', class_weight='balanced')
fruit_model.fit(X_train, y_train)

# Step 5: Make predictions
y_pred = fruit_model.predict(X_test)

# Step 6: Evaluate model
print("\nClassification Report (Fruits):")
print(classification_report(y_test, y_pred))

# Confusion Matrix for Fruits
conf_mat_fruits = confusion_matrix(y_test, y_pred)

# Plot confusion matrix heatmap
plt.figure(figsize=(8, 6))
sns.heatmap(conf_mat_fruits, annot=True, fmt='d', cbar=True,
            xticklabels=np.unique(y),
            yticklabels=np.unique(y))
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix - Fruit Classification')
plt.show()

print("\nSeatwork Complete: SVM successfully implemented on synthetic fruit dataset!")
