# -*- coding: utf-8 -*-
"""Paule_Lab3 - SVM Classifier on Linearly Separable Data

Automatically generated by Colab.

AUTHOR: Faith Paule
COURSE: BCS35
ACTIVITY: Lab 3 - Support Vector Machine (SVM) Classification
TOPIC: Machine Learning (ML) - Supervised Classification, Support Vector Machine (SVM)
OBJECTIVE Support Vector Machine (SVM) classifier with a linear kernel on a synthetic, linearly separable dataset generated using make_blobs. The activity covers the full ML pipeline: data generation, train-test splitting, model training, and visualizing the decision hyperplane, margins, and support vectors.
- Generate synthetic linearly separable data
- Train a linear SVM classifier
- Visualize the decision hyperplane, margins, and support vectors

Language & Tech Stack
Programming Language: Python 3

Tech Stack:
- scikit-learn: For dataset generation (make_blobs), splitting (train_test_split), and the SVM classifier (svm.SVC).
- NumPy: For array operations and saving/loading data.
- Matplotlib: For generating plots, including the scatter plot and the SVM hyperplane visualization.
- Google Colab: The environment (as seen in the file path).
"""

# ============================================================================
# 1. IMPORT LIBRARIES AND CONFIGURE SETTINGS
# ============================================================================
from sklearn.datasets import make_blobs
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import ConfusionMatrixDisplay
import numpy as np
import matplotlib.pyplot as plt

# Configuration parameters for reproducibility and data generation
blobs_random_seed = 42
centers = [(0, 0), (5, 5)]          # Two cluster centers (linearly separable)
cluster_std = 1.5                    # Standard deviation of clusters
frac_test_split = 0.33               # 33% for testing
num_features_for_samples = 2         # 2D features (X1, X2)
num_samples_total = 1000             # Total data points

# ============================================================================
# 2. GENERATE SYNTHETIC DATASET AND SPLIT INTO TRAIN/TEST
# ============================================================================
# Generate linearly separable blobs (two classes)
inputs, targets = make_blobs(
    n_samples=num_samples_total,
    centers=centers,
    n_features=num_features_for_samples,
    cluster_std=cluster_std
)

# Split data (67% train, 33% test) with fixed random state for reproducibility
X_train, X_test, y_train, y_test = train_test_split(
    inputs, targets, test_size=frac_test_split, random_state=blobs_random_seed
)

# ============================================================================
# 3. SAVE AND LOAD DATA (DEMONSTRATION OF NUMPY I/O)
# ============================================================================
np.save('./X_train.npy', X_train)
np.save('./X_test.npy', X_test)
np.save('./y_train.npy', y_train)
np.save('./y_test.npy', y_test)

X_train = np.load('./X_train.npy', allow_pickle=True)
X_test = np.load('./X_test.npy', allow_pickle=True)
y_train = np.load('./y_train.npy', allow_pickle=True)
y_test = np.load('./y_test.npy', allow_pickle=True)

# ============================================================================
# 4. VISUALIZE TRAINING DATA (SCATTER PLOT)
# ============================================================================
plt.figure(figsize=(8, 6))
plt.scatter(X_train[:, 0], X_train[:, 1], c=y_train, cmap=plt.cm.coolwarm, s=30)
plt.title('Linearly Separable Training Data')
plt.xlabel('Feature X1')
plt.ylabel('Feature X2')
plt.colorbar(label='Class')
plt.show()

# ============================================================================
# 5. TRAIN LINEAR SVM CLASSIFIER
# ============================================================================
# Initialize SVM with linear kernel (hard/soft margin depending on data)
clf = svm.SVC(kernel='linear')
clf.fit(X_train, y_train)

# Display support vector indices (points closest to decision boundary)
print("Support Vector Indices (positions in training set):", clf.support_)
print(f"Number of support vectors: {len(clf.support_)}")

# ============================================================================
# 6. VISUALIZE HYPERPLANE, MARGINS, AND SUPPORT VECTORS
# ============================================================================
plt.figure(figsize=(8, 6))

# Plot all training points, colored by class
plt.scatter(X_train[:, 0], X_train[:, 1], c=y_train, cmap=plt.cm.coolwarm, s=30)

# Highlight support vectors (larger circles with black edge)
plt.scatter(
    clf.support_vectors_[:, 0], clf.support_vectors_[:, 1],
    s=100, facecolors='none', edgecolors='k', label='Support Vectors'
)

# Calculate decision boundary: w0*x + w1*y + b = 0  →  y = -(w0*x + b)/w1
w = clf.coef_[0]
b = clf.intercept_[0]
xx = np.linspace(plt.xlim()[0], plt.xlim()[1])
yy = -(w[0] * xx + b) / w[1]

# Plot decision boundary (solid line) and margins (dashed lines)
plt.plot(xx, yy, 'k-', label='Decision Boundary')
margin = 1 / np.linalg.norm(w)
plt.plot(xx, yy + margin, 'k--', label=f'Margin (={margin:.2f})')
plt.plot(xx, yy - margin, 'k--')

plt.title("SVM: Hyperplane, Margins, and Support Vectors")
plt.xlabel('Feature X1')
plt.ylabel('Feature X2')
plt.legend()
plt.grid(alpha=0.3)
plt.show()
